source 'https://mirrors.tuna.tsinghua.edu.cn/rubygems/'

# GitHub pages 提供的打包
gem 'github-pages', group: :jekyll_plugins

group :jekyll_plugins do
  gem 'jemoji'
  gem 'jekyll-sitemap'
  gem 'jekyll-feed'
end
