source 'https://mirrors.tuna.tsinghua.edu.cn/rubygems/'
gem 'github-pages', group: :jekyll_plugins
gem "jekyll"
gem "ffi"
gem "nokogiri", ">= 1.11.0"

group :jekyll_plugins do
  gem 'jemoji'
  gem 'jekyll-sitemap'
  gem 'jekyll-feed'
end

gem "webrick", "~> 1.7"
